### ISSUE TITLE
Create visual means of tracking user input

### ISSUE THREAD

**Issue by aggregate1166877** [frostoven/gamepad-profiler#5]
Details:

We need a visual indication when the controller is plugged in.

**Important note:** This application uses NW.js, which is Chromium-based. At the time of writing, Chromium supports exactly 4 input controllers. This means your UI should allow for 4 simultaneous input devices to be plugged in at the same time. It's not crucial that 4-controller support is implemented during this task, but keeping it in mind may help with development.

The process should go something like this:
* User plugs in controller.
* A log shows that it has now been plugged in.
* The user can press buttons and move the analog stick, and the UI visually updates to indicate this.

**Comment by RebornZA** [comment]
Will close if you are happy with current implementation.
